### PR TITLE
Rename YtechChainlinkExtension to SymbidChainlinkExtension

### PR DESCRIPTION
**Pull request by franciscosantamaria**
Rename the filename of the Extension class **YtechChainlinkExtension** to **SymbidChainlinkExtension** because if not, the container could not find the extension to load the configuration for "symbid_chainlink".

### CODE REVIEW

**Comment by franciscosantamaria** [comment]
I suppose it was a mistake.

Regards,
kiko

**Comment by franciscosantamaria** [comment]
Hi @rdohms , any problem with this?Could you provide feedback? Thanks

**Comment by rdohms** [comment]
Sorry mate, got by my email filter and i did not see it.

**Comment by franciscosantamaria** [comment]
No prob ;)

**Pull request merged**
